name: Build

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch


jobs:
  build:
    runs-on: windows-2025
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install webpack
        run: npm install --save-dev webpack webpack-cli terser-webpack-plugin ignore-loader

      - name: Prepare build folder
        run: mkdir build
          
      - name: Build with Webpack
        run: |
              npx webpack --config webpack.config.js
              cp tmp/fbin.js build/

      - name: Generate tag
        id: tag
        run: |
          (Get-Date -format "\ta\g=buil\d-yyyymmdd-mmhh") | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git refs/tags/${{ steps.tag.outputs.tag }}

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            Automatic release generated from GitHub Actions.
          files: build/fbin.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

