name: Build

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        run: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Install webpack
        run: npm install --save-dev webpack webpack-cli terser-webpack-plugin ignore-loader

      - name: Prepare build folder
        run: mkdir -p build
          
      - name: Build with Webpack
        run: |
              npx webpack --config webpack.config.js
              cp tmp/fbin.js build/

      - name: Generate tag
        id: tag
        run: |
          TAG="v$(date +%Y%m%d%H%M%S)"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Commit and push build artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add build
          git commit -m "Build artifacts for ${{ steps.tag.outputs.tag }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git refs/tags/${{ steps.tag.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            Automatic release generated from GitHub Actions.
          files: build/fbin.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

